import java.util.ArrayList;
import java.util.UUID;

import javax.swing.table.DefaultTableModel;

public class SystemTerminalGui extends javax.swing.JFrame {

    /**
     * Creates new form SystemTerminalGui
     */
    public SystemTerminalGui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
        terminal = new SystemTerminal(new Room(100, 5, 4));
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        LoginScreen = new javax.swing.JPanel();
        HelloText = new javax.swing.JLabel();
        SignInToAccText = new javax.swing.JLabel();
        KeyIdField = new javax.swing.JTextField();
        PasswordField = new javax.swing.JTextField();
        signInBtn = new javax.swing.JButton();
        panelRound3 = new swing_assets.PanelRound();
        jLabel7 = new javax.swing.JLabel();
        configPage = new javax.swing.JPanel();
        sidebar = new javax.swing.JPanel();
        userLabel = new javax.swing.JLabel();
        keyLabel = new javax.swing.JLabel();
        systemLabel = new javax.swing.JLabel();
        logOutLabel = new javax.swing.JLabel();
        dashboardLabel = new javax.swing.JLabel();
        configContent = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        dashboardTab = new javax.swing.JPanel();
        panelRound1 = new swing_assets.PanelRound();
        jLabel1 = new javax.swing.JLabel();
        firstNameLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        usersTab = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        panelRound2 = new swing_assets.PanelRound();
        dashboardLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        userNameSearchField = new swing_assets.TextField();
        panelRound4 = new swing_assets.PanelRound();
        dashboardLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        usersQuery = new swing_assets.Table();
        jPanel1 = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        LoginScreen.setBackground(new java.awt.Color(22, 98, 243));
        LoginScreen.setMaximumSize(new java.awt.Dimension(950, 550));
        LoginScreen.setMinimumSize(new java.awt.Dimension(950, 550));
        LoginScreen.setPreferredSize(new java.awt.Dimension(950, 550));
        LoginScreen.setRequestFocusEnabled(false);

        HelloText.setFont(new java.awt.Font("Segoe UI Black", 1, 60)); // NOI18N
        HelloText.setForeground(new java.awt.Color(255, 255, 255));
        HelloText.setText("Hello");

        SignInToAccText.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        SignInToAccText.setForeground(new java.awt.Color(255, 255, 255));
        SignInToAccText.setText("Sign in to your account.");

        KeyIdField.setBackground(new java.awt.Color(22, 98, 243));
        KeyIdField.setForeground(new java.awt.Color(255, 255, 255));
        // KeyIdField.setText("Enter your key id");
        KeyIdField.setText("38f5b748-0ca9-4873-ad07-014749cf8389");
        KeyIdField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        // KeyIdField.addMouseListener(new java.awt.event.MouseAdapter() {
        //     public void mouseClicked(java.awt.event.MouseEvent evt) {
        //         KeyIdField.setText("");
        //     }
        // });
        KeyIdField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                if(KeyIdField.getText().equals("Enter your KeyCard ID"))
                    KeyIdField.setText("");
            }
        });
        KeyIdField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                if(KeyIdField.getText().equals(""))
                    KeyIdField.setText("Enter your KeyCard ID");
            }
        });

        PasswordField.setBackground(new java.awt.Color(22, 98, 243));
        PasswordField.setForeground(new java.awt.Color(255, 255, 255));
        // PasswordField.setText("Enter your password");
        PasswordField.setText("Johnpass");
        PasswordField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        PasswordField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                if(KeyIdField.getText().equals("Enter your password"))
                    KeyIdField.setText("");
            }
        });
        PasswordField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                if(KeyIdField.getText().equals(""))
                    KeyIdField.setText("Enter your password");
            }
        });

        signInBtn.setBackground(new java.awt.Color(255, 255, 255));
        signInBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        signInBtn.setForeground(new java.awt.Color(0, 0, 0));
        signInBtn.setText("SIGN IN");
        signInBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));
        signInBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                String keyCardID = KeyIdField.getText().toString();
                String pass = PasswordField.getText().toString();
                User user = terminal.authenticateUser(UUID.fromString(keyCardID));
                if(user != null){
                    if(user.getLoginKey().equals(pass)){
                        LoginScreen.setVisible(false);
                        firstNameLabel.setText(user.getFirstName());
                        jTabbedPane2.setSelectedIndex(0);
                        configPage.setVisible(true);
                    } else {
                        System.out.println("Incorrect Password");
                    }
                } else{
                    // 🚩FLAG ERROR
                }
            }
        });

        panelRound3.setBackground(new java.awt.Color(255, 255, 255));
        panelRound3.setRoundBottomLeft(20);
        panelRound3.setRoundTopLeft(20);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/undraw_my_password_re_ydq7@0.8x.png"))); // NOI18N

        javax.swing.GroupLayout panelRound3Layout = new javax.swing.GroupLayout(panelRound3);
        panelRound3.setLayout(panelRound3Layout);
        panelRound3Layout.setHorizontalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound3Layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(33, 33, 33))
        );
        panelRound3Layout.setVerticalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(89, 89, 89))
        );

        javax.swing.GroupLayout LoginScreenLayout = new javax.swing.GroupLayout(LoginScreen);
        LoginScreen.setLayout(LoginScreenLayout);
        LoginScreenLayout.setHorizontalGroup(
            LoginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginScreenLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(LoginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(signInBtn)
                    .addGroup(LoginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(KeyIdField)
                        .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(LoginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(HelloText)
                        .addComponent(SignInToAccText, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(100, 100, 100)
                .addComponent(panelRound3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        LoginScreenLayout.setVerticalGroup(
            LoginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginScreenLayout.createSequentialGroup()
                .addContainerGap(141, Short.MAX_VALUE)
                .addComponent(HelloText)
                .addGap(0, 0, 0)
                .addComponent(SignInToAccText)
                .addGap(30, 30, 30)
                .addComponent(KeyIdField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(signInBtn)
                .addGap(138, 138, 138))
            .addComponent(panelRound3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(LoginScreen, "card2");

        configPage.setBackground(new java.awt.Color(247, 248, 252));
        configPage.setForeground(new java.awt.Color(247, 248, 252));
        configPage.setMaximumSize(new java.awt.Dimension(950, 550));
        configPage.setMinimumSize(new java.awt.Dimension(950, 550));
        configPage.setPreferredSize(new java.awt.Dimension(950, 550));

        sidebar.setBackground(new java.awt.Color(255, 255, 255));
        sidebar.setForeground(new java.awt.Color(255, 255, 255));

        userLabel.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 12)); // NOI18N
        userLabel.setForeground(new java.awt.Color(40, 48, 59));
        userLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        userLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/icons8-search-client-24.png"))); // NOI18N
        userLabel.setText("Users");
        userLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 5, 0, 0));
        userLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane2.setSelectedIndex(1);

                // REMOVÉ ALL ROWS

                int rowCount = usersQuery.getRowCount();
                for (int i = rowCount - 1; i >= 0; i--) {
                    model.removeRow(i);
                }

                // ADD ROWS
                ArrayList<Object[]> rows = terminal.populateTable();
                if(!rows.isEmpty()){
                    for (int i = 0; i < rows.size(); i++) {
                        Object[] row = rows.get(i);
                        usersQuery.addRow(row);
                    }
                } else{
                    System.out.println("Empty rows ArrayList");
                }
            }
        });

        keyLabel.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 12)); // NOI18N
        keyLabel.setForeground(new java.awt.Color(40, 48, 59));
        keyLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        keyLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/icons8-password-key-24.png"))); // NOI18N
        keyLabel.setText("Keys");
        keyLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 5, 0, 0));

        keyLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane2.setSelectedIndex(2);
            }
        });

        systemLabel.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 12)); // NOI18N
        systemLabel.setForeground(new java.awt.Color(40, 48, 59));
        systemLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        systemLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/icons8-system-information-24.png"))); // NOI18N
        systemLabel.setText("System");
        systemLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 5, 0, 0));

        logOutLabel.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 12)); // NOI18N
        logOutLabel.setForeground(new java.awt.Color(40, 48, 59));
        logOutLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        logOutLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/icons8-logout-24.png"))); // NOI18N
        logOutLabel.setText("Sign out");
        logOutLabel.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        logOutLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                configPage.setVisible(false);
                LoginScreen.setVisible(true);
            }
        });

        dashboardLabel.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 12)); // NOI18N
        dashboardLabel.setForeground(new java.awt.Color(40, 48, 59));
        dashboardLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dashboardLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/dashboard.png"))); // NOI18N
        dashboardLabel.setText("Dashboard");
        dashboardLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 5, 0, 0));
        dashboardLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane2.setSelectedIndex(0);
            }
        });

        javax.swing.GroupLayout sidebarLayout = new javax.swing.GroupLayout(sidebar);
        sidebar.setLayout(sidebarLayout);
        sidebarLayout.setHorizontalGroup(
            sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarLayout.createSequentialGroup()
                .addGap(0, 21, Short.MAX_VALUE)
                .addGroup(sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dashboardLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(keyLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(systemLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidebarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logOutLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        sidebarLayout.setVerticalGroup(
            sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarLayout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(dashboardLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(userLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(keyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(systemLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(logOutLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        configContent.setBackground(new java.awt.Color(247, 248, 252));
        configContent.setForeground(new java.awt.Color(247, 248, 252));

        jTabbedPane2.setBackground(new java.awt.Color(247, 247, 247));
        jTabbedPane2.setForeground(new java.awt.Color(0, 0, 0));
        jTabbedPane2.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);
        jTabbedPane2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        dashboardTab.setBackground(new java.awt.Color(247, 247, 247));
        dashboardTab.setForeground(new java.awt.Color(247, 248, 252));

        panelRound1.setBackground(new java.awt.Color(248, 72, 94));
        panelRound1.setRoundBottomLeft(20);
        panelRound1.setRoundBottomRight(20);
        panelRound1.setRoundTopLeft(20);
        panelRound1.setRoundTopRight(20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/undraw_dev_focus_re_6iwt@0.8x.png"))); // NOI18N

        firstNameLabel.setFont(new java.awt.Font("Microsoft YaHei", 1, 24)); // NOI18N
        firstNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        firstNameLabel.setText("Name");

        jLabel4.setFont(new java.awt.Font("Microsoft YaHei", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Welcome back,");

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(firstNameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 137, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(54, 54, 54))
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(firstNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Microsoft YaHei", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Dashboard");

        jLabel5.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel5.setText("20 Sep 2019, Friday");
        jLabel5.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 5));

        javax.swing.GroupLayout dashboardTabLayout = new javax.swing.GroupLayout(dashboardTab);
        dashboardTab.setLayout(dashboardTabLayout);
        dashboardTabLayout.setHorizontalGroup(
            dashboardTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardTabLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(dashboardTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(dashboardTabLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        dashboardTabLayout.setVerticalGroup(
            dashboardTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardTabLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(dashboardTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(453, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("tab1", dashboardTab);

        usersTab.setBackground(new java.awt.Color(247, 247, 247));
        usersTab.setForeground(new java.awt.Color(247, 248, 252));

        jLabel6.setFont(new java.awt.Font("Microsoft YaHei", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Users");

        panelRound2.setBackground(new java.awt.Color(255, 255, 255));
        panelRound2.setRoundBottomLeft(20);
        panelRound2.setRoundBottomRight(20);
        panelRound2.setRoundTopLeft(20);
        panelRound2.setRoundTopRight(20);

        dashboardLabel1.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 12)); // NOI18N
        dashboardLabel1.setForeground(new java.awt.Color(40, 48, 59));
        dashboardLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dashboardLabel1.setText("Who are you looking for?");
        dashboardLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 5, 0, 0));
        dashboardLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dashboardLabel1MouseEntered(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(22, 98, 243));
        jButton2.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 10)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("SEARCH");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        userNameSearchField.setBackground(new java.awt.Color(247, 247, 247));
        userNameSearchField.setText("Enter a name");
        userNameSearchField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                if(userNameSearchField.getText().equals("Enter a name"))
                    userNameSearchField.setText("");
            }
        });
        userNameSearchField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                if(userNameSearchField.getText().equals(""))
                    userNameSearchField.setText("Enter a name");
            }
        });

        javax.swing.GroupLayout panelRound2Layout = new javax.swing.GroupLayout(panelRound2);
        panelRound2.setLayout(panelRound2Layout);
        panelRound2Layout.setHorizontalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound2Layout.createSequentialGroup()
                        .addComponent(dashboardLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelRound2Layout.createSequentialGroup()
                        .addComponent(userNameSearchField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))))
        );
        panelRound2Layout.setVerticalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(dashboardLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userNameSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        panelRound4.setBackground(new java.awt.Color(255, 255, 255));
        panelRound4.setRoundBottomLeft(20);
        panelRound4.setRoundBottomRight(20);
        panelRound4.setRoundTopLeft(20);
        panelRound4.setRoundTopRight(20);

        dashboardLabel2.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 12)); // NOI18N
        dashboardLabel2.setForeground(new java.awt.Color(40, 48, 59));
        dashboardLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dashboardLabel2.setText("Users Summary");
        dashboardLabel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 5, 0, 0));
        dashboardLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dashboardLabel2MouseEntered(evt);
            }
        });

        usersQuery.setBackground(new java.awt.Color(255, 255, 255));
        usersQuery.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        usersQuery.setForeground(new java.awt.Color(0, 0, 0));

        model = new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "First Name", "Last Name", "Clearance Level"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        };
        usersQuery.setModel(model);
        usersQuery.setRowHeight(20);
        usersQuery.setSelectionBackground(new java.awt.Color(22, 98, 243));
        jScrollPane3.setViewportView(usersQuery);

        javax.swing.GroupLayout panelRound4Layout = new javax.swing.GroupLayout(panelRound4);
        panelRound4.setLayout(panelRound4Layout);
        panelRound4Layout.setHorizontalGroup(
            panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dashboardLabel2)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 654, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        panelRound4Layout.setVerticalGroup(
            panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(dashboardLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout usersTabLayout = new javax.swing.GroupLayout(usersTab);
        usersTab.setLayout(usersTabLayout);
        usersTabLayout.setHorizontalGroup(
            usersTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usersTabLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(usersTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelRound2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6)
                    .addComponent(panelRound4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        usersTabLayout.setVerticalGroup(
            usersTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usersTabLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelRound2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelRound4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(247, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("tab2", usersTab);

        jPanel1.setBackground(new java.awt.Color(247, 247, 247));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 771, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 771, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("tab3", jPanel1);

        javax.swing.GroupLayout configContentLayout = new javax.swing.GroupLayout(configContent);
        configContent.setLayout(configContentLayout);
        configContentLayout.setHorizontalGroup(
            configContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(configContentLayout.createSequentialGroup()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );
        configContentLayout.setVerticalGroup(
            configContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(configContentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );

        jTabbedPane2.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout configPageLayout = new javax.swing.GroupLayout(configPage);
        configPage.setLayout(configPageLayout);
        configPageLayout.setHorizontalGroup(
            configPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(configPageLayout.createSequentialGroup()
                .addComponent(sidebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(configContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        configPageLayout.setVerticalGroup(
            configPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sidebar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(configContent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        getContentPane().add(configPage, "card3");

        pack();
    }// </editor-fold>                        

    private void KeyIdFieldActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void PasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    private void signInBtnActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void userLabelMouseClicked(java.awt.event.MouseEvent evt) {                                       
        // TODO add your handling code here:
    }                                      

    private void KeyIdFieldMouseClicked(java.awt.event.MouseEvent evt) {                                        
        KeyIdField.setText("");
    }                                       

    private void dashboardLabelMouseEntered(java.awt.event.MouseEvent evt) {                                            
        dashboardLabel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 0, 0, new java.awt.Color(0, 0, 0)));
    }                                           

    private void dashboardLabel1MouseEntered(java.awt.event.MouseEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void userNameSearchFieldActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void dashboardLabel2MouseEntered(java.awt.event.MouseEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SystemTerminalGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SystemTerminalGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SystemTerminalGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SystemTerminalGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SystemTerminalGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel HelloText;
    private javax.swing.JTextField KeyIdField;
    private javax.swing.JPanel LoginScreen;
    private javax.swing.JTextField PasswordField;
    private javax.swing.JLabel SignInToAccText;
    private javax.swing.JPanel configContent;
    private javax.swing.JPanel configPage;
    private javax.swing.JLabel dashboardLabel;
    private javax.swing.JLabel dashboardLabel1;
    private javax.swing.JLabel dashboardLabel2;
    private javax.swing.JPanel dashboardTab;
    private javax.swing.JButton signInBtn;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JLabel keyLabel;
    private javax.swing.JLabel logOutLabel;
    private swing_assets.PanelRound panelRound1;
    private swing_assets.PanelRound panelRound2;
    private swing_assets.PanelRound panelRound3;
    private swing_assets.PanelRound panelRound4;
    private javax.swing.JPanel sidebar;
    private javax.swing.JLabel systemLabel;
    private swing_assets.TextField userNameSearchField;
    private javax.swing.JLabel userLabel;
    private swing_assets.Table usersQuery;
    private javax.swing.JPanel usersTab;
    private SystemTerminal terminal;
    private DefaultTableModel model;
    // End of variables declaration                   
}
