version: '3.8'
services:             
    cosc304-mysql:
        image: mysql:8.0
        container_name: cosc310-mysql
        restart: always
        environment:
            MYSQL_DATABASE: 'testuser'
            MYSQL_USER: 'testuser'
            MYSQL_PASSWORD: '310testypw'            
            MYSQL_ROOT_PASSWORD: '310rootypw'
        ports:
            - '3306:3306'
        expose:
            - '3306'   
        volumes:
            - mysql-db:/var/lib/mysql
            - ./ddl:/docker-entrypoint-initdb.d
volumes:     
    mysql-db: